### ISSUE TITLE
use custom font

### ISSUE THREAD

**Issue by pishguy** [HeZaiJin/SlantedTextView#11]
how can i use custom fonts on this widget?  for example `http://fontawesome.io/cheatsheet/`

my code dont work for example:

```
if (!isInEditMode()) {
    if (mTextFontFamily != null || !mTextFontFamily.isEmpty()) {
        mTextTypeFace = Utils.findFont(mContext, mTextFontFamily, mDefaultTextFont);
    } else {
        mTextTypeFace = Utils.findFont(mContext, mDefaultTextFont, null);
    }
}
mTextPaint.setTypeface(mTextTypeFace);
mSlantedText="&#xf032;";
```

**Comment by HeZaiJin** [comment]
Is the findFont method return a correct font?  TextPaint support custom text font usually.

**Comment by pishguy** [comment]
@HeZaiJin yes, i'm using `findFont` [from this repository](https://github.com/medyo/Fancybuttons/blob/master/fancybuttons_library/src/main/java/mehdi/sakout/fancybuttons/Utils.java) and that work fine without any problem, i trace it in debug mode

attr:

    <declare-styleable name="SlantedTextView">
        ...
        <attr name="slantedTextFont" format="string"/>
        ...
    </declare-styleable>

`init` method on `SlantedTextView` class:

    public void init(AttributeSet attrs) {
        TypedArray array = getContext().obtainStyledAttributes(attrs, R.styleable.SlantedTextView);

        mTextSize = array.getDimension(R.styleable.SlantedTextView_slantedTextSize, mTextSize);
        mTextColor = array.getColor(R.styleable.SlantedTextView_slantedTextColor, mTextColor);
        mSlantedLength = array.getDimension(R.styleable.SlantedTextView_slantedLength, mSlantedLength);
        mSlantedBackgroundColor = array.getColor(R.styleable.SlantedTextView_slantedBackgroundColor, mSlantedBackgroundColor);

        /* I ADD THIS LINE */
        mTextFontFamily = array.getString(R.styleable.SlantedTextView_slantedTextFont);
        if (array.hasValue(R.styleable.SlantedTextView_slantedText)) {
            mSlantedText = array.getString(R.styleable.SlantedTextView_slantedText);
        }

        if (array.hasValue(R.styleable.SlantedTextView_slantedMode)) {
            mMode = array.getInt(R.styleable.SlantedTextView_slantedMode, 0);
        }
        array.recycle();

        mPaint = new Paint();
        mPaint.setStyle(Paint.Style.FILL);
        mPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));
        mPaint.setAntiAlias(true);
        mPaint.setColor(mSlantedBackgroundColor);

        mTextPaint = new TextPaint(Paint.ANTI_ALIAS_FLAG);
        mTextPaint.setAntiAlias(true);
        mTextPaint.setTextSize(mTextSize);
        mTextPaint.setColor(mTextColor);

        /* I THEN ADDED THIS LINES */
        if (!isInEditMode()) {
            if (mTextFontFamily != null || !mTextFontFamily.isEmpty()) {
                mTextTypeFace = FancyButtonUtils.findFont(mContext, mTextFontFamily, mDefaultTextFont);
            } else {
                mTextTypeFace = FancyButtonUtils.findFont(mContext, mDefaultTextFont, null);
            }
        }

        mTextPaint.setTypeface(mTextTypeFace);
    }

use in XML layout:

    <my.app.widgets.SlantedTextView
        android:id="@+id/slantedView"
        android:layout_width="30dp"
        android:layout_height="30dp"
        android:layout_gravity="right|top"
        app:slantedBackgroundColor="@color/customactivityoncrash_primary"
        app:slantedLength="35dp"
        app:slantedTextFont="fonts/times.ttf"
        app:slantedMode="right"/>

**Comment by HeZaiJin** [comment]
good job!
