### ISSUE TITLE
请问下本库支持图片形式的角标么

### ISSUE THREAD

**Issue by xiaoli-style** [HeZaiJin/SlantedTextView#13]
![t_4k6z 7j8udk ss u t7](https://user-images.githubusercontent.com/35419620/40735969-3c1f42e0-646f-11e8-9a65-e5b279941bdc.png)

如上图，设置一个钩子图片

**Comment by HeZaiJin** [comment]
并不支持，如果是图片角标，你完全可以直接盖在内容右上角就可以，Framelayout,Relativelayout都可以。
