### ISSUE TITLE
布局中如果放在CardView的上层，不显示。

### ISSUE THREAD

**Issue by yecaler** [HeZaiJin/SlantedTextView#14]
布局代码如下时，不显示SlantedTextView.

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="5dp"
    android:layout_marginLeft="10dp"
    android:layout_marginRight="10dp"
    android:layout_marginTop="5dp">

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:cardBackgroundColor="@color/white"
        app:cardCornerRadius="5dp"
        app:cardElevation="2dp"
        app:cardMaxElevation="2dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_margin="8dp"
            android:orientation="vertical">

            <ImageView
                android:layout_width="80dp"
                android:layout_height="80dp"
                android:scaleType="centerCrop"
                android:src="@drawable/image_default" />
        </LinearLayout>
    </android.support.v7.widget.CardView>

    <com.haozhang.lib.SlantedTextView
        android:id="@+id/item_recommend_slanted_tv"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_alignParentRight="true"
        android:gravity="center"
        app:slantedBackgroundColor="#607D88"
        app:slantedLength="40dp"
        app:slantedMode="right"
        app:slantedText="IOS"
        app:slantedTextColor="@color/black"
        app:slantedTextSize="16sp" />

</RelativeLayout>

**Comment by supperyan** [comment]
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="5dp"
    android:layout_marginLeft="10dp"
    android:layout_marginRight="10dp"
    android:layout_marginTop="5dp">
    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:cardBackgroundColor="@color/white"
        app:cardCornerRadius="5dp"
        app:cardElevation="2dp"
        app:cardMaxElevation="2dp">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_margin="8dp"
            android:orientation="vertical">

            <ImageView
                android:layout_width="80dp"
                android:layout_height="80dp"
                android:scaleType="centerCrop"
                android:src="@drawable/image_default" />
        </LinearLayout>
    </android.support.v7.widget.CardView>
    <com.haozhang.lib.SlantedTextView
        android:id="@+id/item_recommend_slanted_tv"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_alignParentRight="true"
        android:gravity="center"
        app:slantedBackgroundColor="#607D88"
        app:slantedLength="40dp"
        app:slantedMode="right"
        app:slantedText="IOS"
        app:slantedTextColor="@color/black"
        app:slantedTextSize="16sp" />
</RelativeLayout>

**Comment by yecaler** [comment]
![image](https://user-images.githubusercontent.com/25024969/50620819-d5be8c80-0f3c-11e9-8048-b37323fff8e7.png)
前面的代码显示不全。我是放在RelativeLayout里面的。

**Comment by yecaler** [comment]
![image](https://user-images.githubusercontent.com/25024969/50620869-3c43aa80-0f3d-11e9-830b-b7c7c811149a.png)
后面部分xml文件的截图如上

**Comment by yecaler** [comment]
![image](https://user-images.githubusercontent.com/25024969/50621089-a01aa300-0f3e-11e9-9de8-b8321a9963b1.png)
显示结果如上

**Comment by yecaler** [comment]
找到原因了！
将CardView的cardElevation设置为0dp后，这样TextView就能正常显示了。
因为：CardView默认有elevation属性，所有会自动处于最上层。

**Comment by yecaler** [comment]
参考地址：
https://blog.csdn.net/jianesrq0724/article/details/75128108
https://blog.csdn.net/qq_33667176/article/details/80820306

**Comment by yecaler** [comment]
但是有个问题就是当CardView的cardElevation设置为0dp后。没有了CardView的阴影凸起效果，看起来不是太美观！大佬能不能解决一下这个问题？

**Comment by yecaler** [comment]
找到了，两个布局需要设置同一Elevation值。
