### ISSUE TITLE
在API28 以上出现位置错乱问题

### ISSUE THREAD

**Issue by qiangzengli** [HeZaiJin/SlantedTextView#17]
![image](https://user-images.githubusercontent.com/38590285/67629838-aad06b00-f8b7-11e9-8891-20a438761c35.png)

如上图  同为  Pixel 2  模拟器    左边Api为  27    右边为28 ，经过测试   发现  在API28  以上会出现有比啊这种问题

**Comment by HeZaiJin** [comment]
Thanks for your report, wish it could be fixed on next release.

**Comment by qiangzengli** [comment]
请问现在能提供修改思路吗，在使用这个库，这个问题现在急需解决

**Comment by HeZaiJin** [comment]
昨晚在android 9.0 小米8 上测试是正常的，没有复现这个问题。

**Comment by HeZaiJin** [comment]
如果是文字偏移，可以从calculateXY method 来入手调整。

**Comment by qiangzengli** [comment]
我也是在小米8上测试的 为什么会出现这个问题呢，之前是Android 9.0  现在升级了10的

**Comment by qiangzengli** [comment]
<com.haozhang.lib.SlantedTextView
                    android:layout_width="@dimen/px_100"
                    android:layout_height="@dimen/px_100"
                    android:gravity="center"
                    app:layout_constraintEnd_toEndOf="@id/personal_center_cat_collection_roundrectview"
                    app:layout_constraintTop_toTopOf="@id/personal_center_cat_collection_roundrectview"
                    app:slantedBackgroundColor="@color/colorAccent"
                    app:slantedLength="@dimen/px_50"
                    app:slantedMode="right"
                    app:slantedText="ANDROID"
                    app:slantedTextColor="@color/white"
                    app:slantedTextSize="@dimen/px_10">

**Comment by qiangzengli** [comment]
这是我的使用代码

**Comment by qiangzengli** [comment]
请问是我的使用代码有问题吗

**Comment by HeZaiJin** [comment]
代码没看出来异常点，可能是在android 10上面有问题，目前手上没有android 10 的设备，晚上我用模拟器看看吧。

**Comment by qiangzengli** [comment]
好的，万分感谢

**Comment by HeZaiJin** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/8649930/67842895-0019b000-fb36-11e9-9e32-9b55fdb4a1ad.png">
我在Android 10 的模拟器上也是正常的，未复现问题。

**Comment by qiangzengli** [comment]
找到问题了      因为使用了这个控件  </com.github.florent37.shapeofview.shapes.RoundRectView>

**Comment by qiangzengli** [comment]
谢谢啦

**Comment by HeZaiJin** [comment]
👌
