### ISSUE TITLE
关于背景色渐变效果

### ISSUE THREAD

**Issue by bilx** [HeZaiJin/SlantedTextView#18]
您好打扰了，请问一下我想把背景色改成渐变的颜色，要怎么做？
 mPaint?.shader = LinearGradient(
                0f, 0f, w.toFloat(), h.toFloat(),
                intArrayOf(mSlantedBackgroundGradient[0], mSlantedBackgroundGradient[1])
                , null
                , Shader.TileMode.MIRROR
            )
我使用了 shader方法，但是没有起作用，
不知道您最近有没有时间帮忙指导一下，非常感谢

**Comment by HeZaiJin** [comment]
你的linearGradient使用有问题
我使用以下测试code是可以渐变的
`
        mPaint.setShader(new LinearGradient(100, 200 , 0, 0, mPaint.getColor(), Color.TRANSPARENT, Shader.TileMode.CLAMP));
`

建议看一下LinearGradientAPI使用规范

**Comment by bilx** [comment]
好的，感谢🙏
