### ISSUE TITLE
当背景设置成黄色，字体设置成其他颜色时看不到字，不知道是不是方式不对

### ISSUE THREAD

**Issue by leguang** [HeZaiJin/SlantedTextView#3]
@HeZaiJin 
当背景设置成黄色，字体设置成其他颜色时看不到字，不知道是不是方式不对

`<com.shtoone.shtw.ui.SlantedTextView
        android:id="@+id/stv_handle_item_recyclerview_yaliji_fragment_viewpager_fragment"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_gravity="bottom|right"
        android:gravity="center"
        app:slantedBackgroundColor="#ffff00"
        app:slantedLength="25dp"
        app:slantedMode="right_bottom_triangle"
        app:slantedText="未处置"
        app:slantedTextColor="#000000"
        app:slantedTextSize="12sp" />`

试过好多种颜色都没用，就是看到黄色背景，看不到字
请问这是Bug吗？

**Comment by HeZaiJin** [comment]
请在xml里面设置slantedText，或者在代码里面调用slv.setText()

**Comment by HeZaiJin** [comment]
不好意思 看错了。是否跟layout_gravity属性有冲突？

**Comment by HeZaiJin** [comment]
我测试了一下，这的确是个BUG。解决方法：
修改SlantedTextView源码内部，删掉这句代码（在init方法里倒数第二行）：
        mTextPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.ADD));

后面会更新version来resolve this BUG.

**Comment by HeZaiJin** [comment]
版本已经更新了，测试了下，这个问题应该是解决了 :)

**Comment by HeZaiJin** [comment]
版本已经更新了，测试了下，这个问题应该是解决了 :)

**Comment by leguang** [comment]
@HeZaiJin 
问题已解决，谢谢了，辛苦了
效率很高^_^

**Comment by HeZaiJin** [comment]
应该的. 那我关闭这个issue了。
