### ISSUE TITLE
我想知道我这么设置为什么不显示字呢？谢谢！

### ISSUE THREAD

**Issue by wdp1990821** [HeZaiJin/SlantedTextView#6]
<com.haozhang.lib.SlantedTextView
        android:id="@+id/slantedTextView"
        android:layout_width="50dp"
        android:layout_height="50dp"
        app:slantedText="android"
        app:slantedLength="30dp"
        app:slantedMode="left_triangle"
        app:slantedTextSize="12sp"
        app:slantedTextColor="@color/colorAccent"
        app:slantedBackgroundColor="#000000"
        android:layout_alignTop="@+id/imageView"
        android:layout_alignEnd="@+id/slantedTextView2" />

**Comment by wdp1990821** [comment]
找到问题了开启硬件加速就好了，请问作者这是为什么呢？

**Comment by HeZaiJin** [comment]
`mPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));`
是否是这段代码有问题？据我所知，硬件加速对Xfremode有影响，可以尝试去掉这句话看看结果。
抱歉我这边没有环境. : )

**Comment by wdp1990821** [comment]
谢谢！屏蔽了这段代码还是出不来文字。

**Comment by HeZaiJin** [comment]
嗯，这样就需要深入去了解硬件加速跟view的绘制之间的关系了。这块我也没有找到这种现象的解释。只能多查查资料看看了。不好意思，没能帮助到你。

**Comment by CuteRem** [comment]
mTextPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.ADD));
我觉得字显示不出来应该处理字所用的画笔，屏蔽掉这句是可以显示出来的，不知道会不会有问题。

**Comment by HeZaiJin** [comment]
这个是文字和背景色叠加模式的配置。渲染相关的，跟ROM版本以及硬件应该是有一点关系，我测试用的是genymotion.没有这块的问题.
