### ISSUE TITLE
java.lang.IllegalStateException: SlantedTextView's width must equal to height, w: 96, h: 155 

### ISSUE THREAD

**Issue by sm-tester** [HeZaiJin/SlantedTextView#9]
Hi, thanks for great library, I have a question : I can't use latest your library, always say width and height not equals, but its equal in layout:

     <com.haozhang.lib.SlantedTextView
        android:id="@+id/prStatusTV"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_alignParentTop="true"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:layout_above="@+id/productNameTV"
        android:gravity="center"
        android:text="@string/i_sold_this_pr_txt"
        android:textColor="@color/colorWhite"
        android:fontFamily="sans-serif-condensed"
        app:slantedBackgroundColor="@color/colorAccent"
        app:slantedMode="left_triangle"
        app:slantedText="IOS"
        app:slantedTextColor="@color/colorWhite"
        app:slantedLength="28dp"
        app:slantedTextSize="10sp"
        />

where problem?

**Comment by HeZaiJin** [comment]
I can not see any problem in layout. Could you change SlantedTextView height in code ? Please check you usages.

**Comment by sm-tester** [comment]
Hi @HeZaiJin!
I found my mistake yesterday, mistake in my code:

    android:layout_alignParentTop="true"
    android:layout_alignParentStart="true"
    android:layout_alignParentLeft="true"
    android:layout_above="@+id/productNameTV"

I need remove:
android:layout_above="@+id/productNameTV"

this a line, because it is changed layout height in parent RelativeLayout layout.
You can delete or close this is question, sorry my mistake. Thank you for great library! 👍

**Comment by HeZaiJin** [comment]
Thanks!
